#### QUESTION 1 ####

library(RSQLite)
db <- dbConnect(SQLite(), dbname="pred.sqlite")

### find intersection of id's across all 3 tables and write to csv ###
id_all <- dbGetQuery(conn = db, "SELECT *
                      FROM pred
                      JOIN demo ON (demo.id = pred.id)
                      JOIN outcome ON (outcome.id = pred.id)")[,1]

write.csv(id_all, file = "idall.csv", row.names = F)

### find id's missing from outcome table ###

id_missing <- dbGetQuery(conn = db, "SELECT  id
                                    FROM  pred  
                                    WHERE id NOT IN (SELECT id FROM outcome)")[[1]]

write.csv(id_missing, file = "idmissing.csv", row.names = F)

#### QUESTION 2 ####

# [30%] Build a model for predicting the first outcome score (the second column in Table outcome), 
# using the data from the first ID list in Problem 1. Generate the corresponding predicted values 
# using your model for the missing IDs in Problem 1.
# 
# Output one csv file: output1.csv should contain one matrix element. The first column of this 
# matrix is the second ID list from Problem 1 and the second column is the predicted values 
# generated by your model.

data2 <-  as.data.frame(dbGetQuery(conn = db, "SELECT  DISTINCT *
                                    FROM  pred JOIN demo ON (demo.id = pred.id)  
                     WHERE pred.id IN (SELECT pred.id
                      FROM pred
                     JOIN demo ON (demo.id = pred.id)
                     JOIN outcome ON (outcome.id = pred.id))"))

outcome2 <- dbGetQuery(conn = db, "SELECT * FROM outcome WHERE outcome.id IN 
                      (SELECT pred.id
                      FROM pred
                       JOIN demo ON (demo.id = pred.id)
                       JOIN outcome ON (outcome.id = pred.id))")[,2]
 